# 📁 Конфигурация Enhanced Obsidian MCP Server
# Скопируйте этот файл как obsidian_mcp_config.yaml и настройте пути

vault:
  # 📝 Путь к вашему Obsidian Vault (обязательно)
  path: 'C:\Users\YourName\Documents\Obsidian Vault'
  
  # 🔍 Настройки поиска (опционально)  
  search:
    index_content: true           # Индексировать содержимое заметок
    case_sensitive: false         # Регистрозависимый поиск
    multilingual: true            # Поддержка русского/английского
    max_results: 20               # Максимум результатов поиска

# ⚙️ Настройки MCP сервера (опционально)
server:
  name: "enhanced-obsidian-mcp"
  version: "1.0.0"
  
  # 🚦 Лимиты безопасности
  limits:
    max_notes_list: 50           # Максимум заметок в list_notes
    max_search_results: 30       # Максимум результатов в explore_notes
    content_preview_chars: 300   # Символов в превью содержимого

# 📊 Логирование (опционально)
logging:
  level: "INFO"                  # DEBUG, INFO, WARNING, ERROR
  file: null                     # null = только в консоль, иначе путь к файлу
